---
sudo: required
os: linux
before_install:
    - sudo apt-get update -y
    - sudo apt-get upgrade --assume-yes
before_script:
    - curl -q --spider http://github.com
    - bats --pretty b2h

notifications:
    email:
        - funscript@outlook.fr
    irc: "chat@jukoo.freenode.net"
